name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      # 2 Para renombrar la rama a latest hago un segundo build con el tag latest (El 2º build usa el caché)
      run: |
        docker build -t anguiano/docker-graphql:0.0.2 .
        docker build -t anguiano/docker-graphql:latest .

    - name: Push Docker Image
      # 1 Para renombrar la rama a latest hago un segundo push con el tag latest
      run: |
        docker push anguiano/docker-graphql:0.0.2
        docker push anguiano/docker-graphql:latest

# 3 Hago un commit "Renombrar a latest" del cambio y se subirán a dockerhub
    